"""The app's visual identity: palette, the mark, the wordmark, coloured action cards and step indicators.

Everything here is plain Tk drawing (Canvas, Label) so it works with any ttk theme and needs no extra dependency.
The mark comes from scrubdicom/app/assets/mark.png, generated by packaging/icons/make_icons.py.
"""
from __future__ import annotations

import tkinter as tk
from pathlib import Path
from tkinter import ttk

NAVY = "#0E3A5C"
NAVY_DEEP = "#0C2642"
TEAL = "#00BAA8"
TEAL_DARK = "#008F82"
AMBER = "#FFB22E"
SLATE = "#5E6C7E"
OFF = "#ECF2F7"
INK = "#111827"
RED = "#CF222E"
WHITE = "#FFFFFF"

_ASSETS = Path(__file__).with_name("assets")
_cache: dict[tuple[int, str], tk.PhotoImage] = {}


def mark_image(root: tk.Misc, size: int) -> tk.PhotoImage | None:
    """The mark as a PhotoImage at 192, 96, 64, 48, 32 or 24 px (integer subsamples of the 192 px asset)."""
    key = (size, id(root.tk))          # per Tcl interpreter: a new window after the old one closed gets its own image
    if key in _cache:
        return _cache[key]
    try:
        img = tk.PhotoImage(master=root, file=str(_ASSETS / "mark.png"))
        factor = max(1, round(192 / size))
        if factor > 1:
            img = img.subsample(factor, factor)
    except tk.TclError:
        return None
    _cache[key] = img
    return img


class Wordmark(ttk.Frame):
    """'Scrub' in navy and 'DICOM' in teal, optionally with the mark to the left."""

    def __init__(self, parent, size: int = 20, with_mark: int | None = None, fg_scrub: str = NAVY_DEEP, **kw):
        super().__init__(parent, **kw)
        self.img = mark_image(self, with_mark) if with_mark else None
        if self.img is not None:
            ttk.Label(self, image=self.img).pack(side="left", padx=(0, max(6, size // 2)))
        f = ("Helvetica Neue", size, "bold")
        ttk.Label(self, text="Scrub", font=f, foreground=fg_scrub).pack(side="left")
        ttk.Label(self, text="DICOM", font=f, foreground=TEAL).pack(side="left", padx=(max(4, size // 4), 0))


class Tile(tk.Canvas):
    """A coloured action card: title, subtitle, a hover lift and a click handler. Drawn on a Canvas so it can carry
    real brand colour regardless of the ttk theme."""

    def __init__(self, parent, title: str, subtitle: str, colour: str, command, width: int = 260, height: int = 120,
                 fg: str = WHITE, hover: str | None = None, mark: int | None = None, **kw):
        bg = _parent_bg(parent)
        super().__init__(parent, width=width, height=height, highlightthickness=0, bg=bg, cursor="hand2", **kw)
        self.colour, self.hover_colour, self.command = colour, hover or _lighten(colour, 0.12), command
        self.w, self.h = width, height
        self._draw(colour)
        self.title_id = self.create_text(22, 34, anchor="nw", text=title, fill=fg, font=("Helvetica Neue", 17, "bold"))
        self.sub_id = self.create_text(22, 64, anchor="nw", text=subtitle, fill=fg, font=("Helvetica Neue", 12), width=width - 44)
        self.img = mark_image(self, mark) if mark else None
        if self.img is not None:
            self.create_image(width - 16, height - 16, anchor="se", image=self.img)
        self.bind("<Enter>", lambda _e: self._draw(self.hover_colour))
        self.bind("<Leave>", lambda _e: self._draw(self.colour))
        self.bind("<Button-1>", lambda _e: self.command())

    def _draw(self, colour: str) -> None:
        self.delete("card")
        r = 18
        w, h = self.w, self.h
        for shape in (self.create_rectangle(r, 0, w - r, h, fill=colour, outline=colour, tags="card"),
                      self.create_rectangle(0, r, w, h - r, fill=colour, outline=colour, tags="card")):
            pass
        for cx, cy in ((r, r), (w - r, r), (r, h - r), (w - r, h - r)):
            self.create_oval(cx - r, cy - r, cx + r, cy + r, fill=colour, outline=colour, tags="card")
        self.tag_lower("card")


class StepPills(tk.Canvas):
    """1 - 2 - 3 with the current step filled teal, the done ones navy, the rest outlined."""

    def __init__(self, parent, n: int = 3, current: int = 0, labels: tuple[str, ...] = (), **kw):
        bg = _parent_bg(parent)
        self.n, self.labels = n, labels
        width = 56 * n + 40
        super().__init__(parent, width=width, height=44, highlightthickness=0, bg=bg, **kw)
        self.set(current)

    def set(self, current: int) -> None:
        self.delete("all")
        for i in range(self.n):
            x = 22 + i * 56
            if i < self.n - 1:
                self.create_line(x + 14, 16, x + 56 - 14, 16, fill=SLATE, width=2)
            fill, outline, fg = (TEAL, TEAL, WHITE) if i == current else ((NAVY_DEEP, NAVY_DEEP, WHITE) if i < current else (self["bg"], SLATE, SLATE))
            self.create_oval(x - 14, 2, x + 14, 30, fill=fill, outline=outline, width=2)
            self.create_text(x, 16, text=str(i + 1), fill=fg, font=("Helvetica Neue", 12, "bold"))
            if self.labels and i < len(self.labels):
                self.create_text(x, 38, text=self.labels[i], fill=SLATE, font=("Helvetica Neue", 9))


def rule(parent, colour: str = TEAL, height: int = 3) -> tk.Frame:
    """A thin coloured line, used under the header."""
    return tk.Frame(parent, bg=colour, height=height, bd=0, highlightthickness=0)


def _parent_bg(widget) -> str:
    try:
        return ttk.Style(widget).lookup("TFrame", "background") or widget.winfo_toplevel().cget("bg")
    except tk.TclError:
        return "#fafafa"


def _lighten(hex_colour: str, amount: float) -> str:
    h = hex_colour.lstrip("#")
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    r, g, b = (int(c + (255 - c) * amount) for c in (r, g, b))
    return f"#{r:02X}{g:02X}{b:02X}"
